### ISSUE TITLE
ExpandableLayout stucks

### ISSUE THREAD

**Issue by Tjart** [cachapa/ExpandableLayout#45] opened 2017-10-13 09:27 UTC
When I expand an ExpandaleLayout a second time the animation of stucks, but expanding the first time is no problem.

Does anyone know this problem and can help me.

**Comment by cachapa** [comment] 2017-10-13 09:37
You need to give a bit more details, otherwise there's little chance to help you.
Can you share some code, and maybe a video of the problem happening?

**Comment by Tjart** [comment] 2017-10-13 09:50
Here is my code

`

    RecyclerView recyclerView;
    private List<NewsListItem> newsListItems;
    private Context context;

    static ViewHolder selectedHolder = null;

    public NewsListAdapter(List<NewsListItem> listItems, Context context) {
        this.newsListItems = listItems;
        this.context = context;
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View v = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.news_list_item, parent, false);
        return new ViewHolder(v);
    }

    @Override
    public void onBindViewHolder(final ViewHolder holder, final int position) {
        final NewsListItem newsListItem = newsListItems.get(position);

        holder.textViewHead.setText(newsListItem.getHead());
        Picasso.with(context).load(newsListItem.getImageUrl()).into(holder.imageView);
        holder.textViewText.setText(newsListItem.getText());

        holder.textViewHead.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (selectedHolder == null){
                    holder.textViewHead.setSelected(true);
                    holder.expandableLayout.expand();
                    selectedHolder = holder;
                }
                else if (holder == selectedHolder){
                    holder.textViewHead.setSelected(false);
                    holder.expandableLayout.collapse();
                    selectedHolder = null;
                }
                else{
                    selectedHolder.textViewHead.setSelected(false);
                    selectedHolder.expandableLayout.collapse();
                    holder.textViewHead.setSelected(true);
                    holder.expandableLayout.expand();
                    selectedHolder = holder;
                }
            }
        });
        holder.expandableLayout.setInterpolator(new OvershootInterpolator());
        holder.expandableLayout.setOnExpansionUpdateListener(new ExpandableLayout.OnExpansionUpdateListener() {
            @Override
            public void onExpansionUpdate(float expansionFraction, int state) {
                Log.d("ExpandableLayout", "State: " + state);
            }
        });
        runEnterAnimation(holder.itemView, position);
    }

    @Override
    public int getItemCount() {
        return newsListItems.size();
    }

    public class ViewHolder extends RecyclerView.ViewHolder{

        public ExpandableLayout expandableLayout;
        public TextView textViewHead;
        public ImageView imageView;
        public TextView textViewText;

        public ViewHolder(View itemView) {
            super(itemView);

            expandableLayout = (ExpandableLayout) itemView.findViewById(R.id.news_list_item_ExpendableLayout);
            textViewHead = (TextView) itemView.findViewById(R.id.news_textView_head);
            imageView = (ImageView) itemView.findViewById(R.id.news_imageView);
            textViewText = (TextView) itemView.findViewById(R.id.news_textView_text);
        }
    }
    private void runEnterAnimation(View view, int position){
        view.setTranslationX(context.getResources().getDisplayMetrics().widthPixels);
        view.animate().translationX(0).setInterpolator(new DecelerateInterpolator(3.f)).
                setDuration(700).setStartDelay((MainActivity.recyclerAnimDelay)+position*700/5).start();
        if (position == (newsListItems.size()-1)){
            MainActivity.recyclerAnimDelay = 0;
        }
    }

`

And this link leads to the video

[https://www.dropbox.com/s/bl0ee4s0u1o7jm9/2017_10_13_11_46_13.mp4?dl=0](url)

**Comment by cachapa** [comment] 2017-10-13 12:12
The problem seems to be that you're changing the item layout during the expansion animation.
From just a cursory look at your code it seems the problem is with the `runEnterAnimation` method. Try removing that method and see if it fixes the issue.

In any case this doesn't seem to be an issue with ExpandableLayout so I'm closing this.

**Closed by cachapa** 2017-10-13 12:12 UTC

**Comment by the-kool-sk** [comment] 2022-01-04 12:11
Add little delay it will fix the issue
