### ISSUE TITLE
Setting expansion level smoothly?

### ISSUE THREAD

**Issue by najmsheikh** [cachapa/ExpandableLayout#55] opened 2018-01-27 06:56 UTC
I was trying to emulate a semi collapsed/expanded view - similar to how Google Play Store uses READ MORE / READ LESS for its app descriptions page.

I set it up so that the expansion level is set to 20% using the `setExpansion()` method. However, the state change is rather abrupt. I realize this is intended behavior but is there a way to pass an expansion level and it smoothly expands/collapses to that point?

**Comment by cachapa** [comment] 2018-01-27 13:37
Currently not. The only way to achieve this currently would be to use your own animator.
I'm closing this issue as it's a duplicate of #35.

**Closed by cachapa** 2018-01-27 13:37 UTC
