### ISSUE TITLE
How to show a bit of the layout in the collapsed state

### ISSUE THREAD

**Issue by Hayko985** [cachapa/ExpandableLayout#68] opened 2018-07-31 13:44 UTC
Hi. I want to show a bit of the layout in the collapsed state. Example I want to show first 4 comments of user and then expand to view more. So how can I do it?  I saw the library methods and there is one method called setExpansion(float value). But 1) this is not for collapse state, 2) this method expands and shows only the last part of the view (imagine I have recyclerView in my expandableLayout), 3) After collapse or expand or toggle the setExpansion() method not works.

**Comment by cachapa** [comment] 2018-08-01 07:27
Closing as duplicate of #35

**Closed by cachapa** 2018-08-01 07:27 UTC
