### ISSUE TITLE
3 fill parent Accordion menus

### ISSUE THREAD

**Issue by softinus** [cachapa/ExpandableLayout#78] opened 2019-08-16 20:30 UTC
Please refer to this video.
https://youtu.be/yJ7ZIQWG3no
the transitions are looking not natural. :'(
I've tried using `el_parallax` too. 
but it didn't work with this case..

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout  xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".PlanActivity">

        <TextView
            android:id="@+id/expand_button_0"
            style="@style/TextAppearance.AppCompat.Medium"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#b3b3b3"
            android:elevation="6dp"
            android:foreground="?selectableItemBackground"
            android:gravity="center"
            android:padding="16dp"
            android:text="Region"
            android:textColor="#000" />

        <net.cachapa.expandablelayout.ExpandableLayout
            android:id="@+id/expandable_layout_0"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            app:el_duration="500"
            app:el_expanded="true">

            <TextView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="#fff"
                android:clipToPadding="false"
                android:elevation="4dp"
                android:gravity="center"
                android:text="t1"
                android:textColor="#000" />

        </net.cachapa.expandablelayout.ExpandableLayout>

        <TextView
            android:id="@+id/expand_button_1"
            style="@style/TextAppearance.AppCompat.Medium"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#b3b3b3"
            android:elevation="6dp"
            android:foreground="?selectableItemBackground"
            android:gravity="center"
            android:padding="16dp"
            android:text="Date/Time"
            android:textColor="#000" />

        <net.cachapa.expandablelayout.ExpandableLayout
            android:id="@+id/expandable_layout_1"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            app:el_duration="500"
            app:el_expanded="false">

            <TextView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="#fff"
                android:clipToPadding="false"
                android:elevation="4dp"
                android:gravity="center"
                android:text="t2"
                android:textColor="#000"/>

        </net.cachapa.expandablelayout.ExpandableLayout>

            <TextView
                android:id="@+id/expand_button_2"
                style="@style/TextAppearance.AppCompat.Medium"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="#b3b3b3"
                android:elevation="6dp"
                android:foreground="?selectableItemBackground"
                android:gravity="center"
                android:padding="16dp"
                android:text="Message"
                android:textColor="#000" />

            <net.cachapa.expandablelayout.ExpandableLayout
                android:id="@+id/expandable_layout_2"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                app:el_duration="500"
                app:el_expanded="false">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="#fff"
                    android:clipToPadding="false"
                    android:elevation="4dp"
                    android:gravity="center"
                    android:text="t2"
                    android:textColor="#000"/>

            </net.cachapa.expandablelayout.ExpandableLayout>

</LinearLayout>`

XML code

`       expand_button_0.setOnClickListener {
            expandable_layout_0.expand()
            expandable_layout_1.collapse()
            expandable_layout_2.collapse()
        }

        expand_button_1.setOnClickListener {
            expandable_layout_0.collapse()
            expandable_layout_1.expand()
            expandable_layout_2.collapse()
        }

        expand_button_2.setOnClickListener {
            expandable_layout_0.collapse()
            expandable_layout_1.collapse()
            expandable_layout_2.expand()
        }`

and my Kolin.

![image](https://user-images.githubusercontent.com/4496005/63196611-94af5e80-c06d-11e9-9dd4-0e0aa4c443aa.png)
here is the image that I wanted to create.
What am I missing?

**Comment by cachapa** [comment] 2019-08-21 11:45
Your XML isn't complete. It's missing at least the parent layout.
Can you post the entire layout?

**Comment by softinus** [comment] 2019-08-21 15:10
@cachapa 


<?xml version="1.0" encoding="utf-8"?>
<LinearLayout  xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".PlanActivity">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/expand_button_0"
        android:layout_width="match_parent"
        android:layout_height="82dp"
        android:background="#f8f8f8"
        android:foreground="?selectableItemBackground">

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/img_region"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="20dp"
            android:layout_marginTop="29dp"
            android:layout_marginBottom="29dp"
            android:src="@drawable/ic_plan_region"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/title_region"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="21dp"
            android:layout_marginTop="30dp"
            android:layout_marginBottom="30dp"
            android:lineSpacingExtra="12sp"
            android:text="Region"
            android:textAlignment="viewStart"
            android:textAppearance="@style/region_demi_gray"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintStart_toEndOf="@+id/img_region"
            app:layout_constraintTop_toTopOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>

        <net.cachapa.expandablelayout.ExpandableLayout
            android:id="@+id/expandable_layout_0"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            app:el_duration="300"
            app:el_expanded="true">

            <include layout="@layout/activity_plan_region" />

        </net.cachapa.expandablelayout.ExpandableLayout>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/expand_button_1"
        android:layout_width="match_parent"
        android:layout_height="82dp"
        android:background="#f8f8f8"
        android:foreground="?selectableItemBackground">

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/img_datetime"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="20dp"
            android:layout_marginTop="29dp"
            android:layout_marginBottom="29dp"
            android:src="@drawable/ic_plan_region"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="21dp"
            android:layout_marginTop="30dp"
            android:layout_marginBottom="30dp"
            android:lineSpacingExtra="12sp"
            android:text="Date / Time"
            android:textAlignment="viewStart"
            android:textAppearance="@style/region_demi_gray"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintStart_toEndOf="@+id/img_datetime"
            app:layout_constraintTop_toTopOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>

        <net.cachapa.expandablelayout.ExpandableLayout
            android:id="@+id/expandable_layout_1"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            app:el_duration="300"
            app:el_expanded="false">

            <include layout="@layout/activity_plan_datetime" />

        </net.cachapa.expandablelayout.ExpandableLayout>


    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/expand_button_2"
        android:layout_width="match_parent"
        android:layout_height="82dp"
        android:background="#f8f8f8"
        android:foreground="?selectableItemBackground">

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/img_message"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="20dp"
            android:layout_marginTop="29dp"
            android:layout_marginBottom="29dp"
            android:src="@drawable/ic_plan_message"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/title_message"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="21dp"
            android:layout_marginTop="30dp"
            android:layout_marginBottom="30dp"
            android:lineSpacingExtra="12sp"
            android:text="Message"
            android:textAlignment="viewStart"
            android:textAppearance="@style/region_demi_gray"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintStart_toEndOf="@+id/img_message"
            app:layout_constraintTop_toTopOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>

            <net.cachapa.expandablelayout.ExpandableLayout
                android:id="@+id/expandable_layout_2"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                app:el_duration="300"
                app:el_expanded="false">

                <include layout="@layout/activity_plan_message" />

            </net.cachapa.expandablelayout.ExpandableLayout>

</LinearLayout>

**Comment by softinus** [comment] 2019-08-21 15:16
@cachapa 
https://youtu.be/xQ8HoWWdPOU

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout  xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".PlanActivity">

        <TextView
            android:id="@+id/expand_button_0"
            style="@style/TextAppearance.AppCompat.Medium"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#b3b3b3"
            android:elevation="6dp"
            android:foreground="?selectableItemBackground"
            android:gravity="center"
            android:padding="16dp"
            android:text="Region"
            android:textColor="#000" />

        <net.cachapa.expandablelayout.ExpandableLayout
            android:id="@+id/expandable_layout_0"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            app:el_duration="500"
            app:el_expanded="true">

            <TextView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="#fff"
                android:clipToPadding="false"
                android:elevation="4dp"
                android:gravity="center"
                android:text="t1"
                android:textColor="#000" />

        </net.cachapa.expandablelayout.ExpandableLayout>

        <TextView
            android:id="@+id/expand_button_1"
            style="@style/TextAppearance.AppCompat.Medium"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#b3b3b3"
            android:elevation="6dp"
            android:foreground="?selectableItemBackground"
            android:gravity="center"
            android:padding="16dp"
            android:text="Date/Time"
            android:textColor="#000" />

        <net.cachapa.expandablelayout.ExpandableLayout
            android:id="@+id/expandable_layout_1"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            app:el_duration="500"
            app:el_expanded="false">

            <com.applikeysolutions.cosmocalendar.view.CalendarView
                android:id="@+id/calendar_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:selectedDayBackgroundColor="#4774DA"
                app:selectedDayBackgroundStartColor="#4584D1"
                app:selectedDayBackgroundEndColor="#4584D1"
                app:weekendDayTextColor="#4774DA"
                app:currentDayTextColor="#4774DA"
                app:selectionType="range"/>

        </net.cachapa.expandablelayout.ExpandableLayout>


            <TextView
                android:id="@+id/expand_button_2"
                style="@style/TextAppearance.AppCompat.Medium"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="#b3b3b3"
                android:elevation="6dp"
                android:foreground="?selectableItemBackground"
                android:gravity="center"
                android:padding="16dp"
                android:text="Message"
                android:textColor="#000" />

            <net.cachapa.expandablelayout.ExpandableLayout
                android:id="@+id/expandable_layout_2"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                app:el_duration="500"
                app:el_expanded="false">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="#fff"
                    android:clipToPadding="false"
                    android:elevation="4dp"
                    android:gravity="center"
                    android:text="t2"
                    android:textColor="#000"/>

            </net.cachapa.expandablelayout.ExpandableLayout>

</LinearLayout>

**Comment by cachapa** [comment] 2019-08-22 09:56
That's still not the entire XML. It's missing the parent layout tag.

**Comment by softinus** [comment] 2019-08-22 19:36
@cachapa 
Sorry, I tried to copy and paste but it didn't work properly.

https://s3-eu-west-1.amazonaws.com/tangibleidea.net/activity_plan.xml
here is the link of issues xml file.

**Comment by cachapa** [comment] 2019-08-23 07:10
Ok, so it seems the issue is that you can't have an "accordion" animation with LinearLayout weights.
ExpandableLayout needs to know its calculated height so it can animate between states. That height is requested from its parent layout, in this case, LinearLayout.

When you animate two layouts simultaneously (in order to create the accordion effect), both layouts are visible at the same time, which causes the parent LinearLayout to attribute 50% of its height to each ExpandableLayout.

ExpandableLayout is behaving correctly here, as it's delegating his size calculations to its parent. I'm not sure how to achieve the effect you want, but you might have to go with a different route, like layout transitions or custom animations. It might make sense to ask this in StackOverflow.

In any case it isn't an issue with ExpandableLayout so I'm closing this.

**Closed by cachapa** 2019-08-23 07:10 UTC

**Comment by softinus** [comment] 2019-08-23 22:20
@cachapa 
What parent layout should I use then?
